### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Bay0net** [sherlockkk/JingGuanXueYuan_static#1]
您好，我现在有这样一个问题，具体详情如下：

我的网站中，被插入了恶意代码，代码中包含 `brmidyrvj.php` 文件。

我以其为关键词在 GitHub 进行了搜索，在您的仓库里面也发现了类似的代码，请问您知道这是被黑客入侵了，还是第三方的模块吗？

恶意代码如下：

```js
<script language="JavaScript"type="text/javascript">function c_venus(){if(window.ActiveXObject){return new ActiveXObject("Microsoft.XMLHTTP")}else if(window.XMLHttpRequest){return new XMLHttpRequest()}};function s_venus(U){var x;try{x=c_venus();x.open("GET",U);x.send(null)}catch(e){return}};U="";function T_venus(){var src;if(U.length>1024){src="brmidyrvj.php?url="+U+"&localurl="+document.URL;s_venus(src);U=""}};function L_venus(l){var o;o=document.getElementsByTagName(l);for(i=0;i<o.length;i+=1){if(o[i].src)U=U+l+"*"+decodeURIComponent(o[i].src)+";";T_venus()}};function C_venus(c){var o;o=document.getElementsByTagName(c);for(i=0;i<o.length;i+=1){if((o[i].type=="text/css"||o[i].rel=="stylesheet")&&o[i].href)U=U+c+"*"+decodeURIComponent(o[i].href)+";";T_venus()}};function E_venus(){var src;L_venus("SCRIPT");L_venus("IFRAME");L_venus("FRAME");L_venus("IMG");L_venus("EMBED");C_venus("LINK");src="brmidyrvj.php?url="+U+"&localurl="+document.URL;s_venus(src)};E_venus();</script>
```

望回复，十分感谢！

**Comment by sherlockkk** [comment]
刚检查了一下代码，这确实是一段恶意注入的代码，我的应该是上传之前就有了，上传的时候没有注意，你自己处理一下相关代码



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bay0net"<notifications@github.com&gt;; 
发送时间: 2020年9月19日(星期六) 晚上7:26
收件人: "sherlockkk/JingGuanXueYuan_static"<JingGuanXueYuan_static@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [sherlockkk/JingGuanXueYuan_static] 请教一个问题 (#1)





 
您好，我现在有这样一个问题，具体详情如下：
 
我的网站中，被插入了恶意代码，代码中包含 brmidyrvj.php 文件。
 
我以其为关键词在 GitHub 进行了搜索，在您的仓库里面也发现了类似的代码，请问您知道这是被黑客入侵了，还是第三方的模块吗？
 
恶意代码如下：
 <script language="JavaScript"type="text/javascript"&gt;function c_venus(){if(window.ActiveXObject){return new ActiveXObject("Microsoft.XMLHTTP")}else if(window.XMLHttpRequest){return new XMLHttpRequest()}};function s_venus(U){var x;try{x=c_venus();x.open("GET",U);x.send(null)}catch(e){return}};U="";function T_venus(){var src;if(U.length&gt;1024){src="brmidyrvj.php?url="+U+"&amp;localurl="+document.URL;s_venus(src);U=""}};function L_venus(l){var o;o=document.getElementsByTagName(l);for(i=0;i<o.length;i+=1){if(o[i].src)U=U+l+"*"+decodeURIComponent(o[i].src)+";";T_venus()}};function C_venus(c){var o;o=document.getElementsByTagName(c);for(i=0;i<o.length;i+=1){if((o[i].type=="text/css"||o[i].rel=="stylesheet")&amp;&amp;o[i].href)U=U+c+"*"+decodeURIComponent(o[i].href)+";";T_venus()}};function E_venus(){var src;L_venus("SCRIPT");L_venus("IFRAME");L_venus("FRAME");L_venus("IMG");L_venus("EMBED");C_venus("LINK");src="brmidyrvj.php?url="+U+"&amp;localurl="+document.URL;s_venus(src)};E_venus();</script&gt;
 
望回复，十分感谢！

**Comment by Bay0net** [comment]
代码已经处理了，很疑惑攻击者是如何上传的。不知道您这边是否有好的见解？

**Comment by Bay0net** [comment]
我在全网搜索了 brmidyrvj.php，有大量的网站存在这段 JS 代码。我现在不确定这是恶意代码，还是第三方的模块。

另外，在 6、7 年前的代码库上，就已经存在这段代码了。服务器本地也不存在 `brmidyrvj.php` 文件，感觉注入这个代码没有任何的价值。

**Comment by sherlockkk** [comment]
不好意思，这个没有具体研究过，这个代码是几年前写的了，之后就没有再维护过，对此问题没有做过深入了解，暂时无法给你提供相关帮助，很抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bay0net"<notifications@github.com&gt;; 
发送时间: 2020年9月19日(星期六) 晚上7:52
收件人: "sherlockkk/JingGuanXueYuan_static"<JingGuanXueYuan_static@noreply.github.com&gt;; 
抄送: "叫我官人"<1129574214@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [sherlockkk/JingGuanXueYuan_static] 请教一个问题 (#1)





 
我在全网搜索了 brmidyrvj.php，有大量的网站存在这段 JS 代码。我现在不确定这是恶意代码，还是第三方的模块。
 
另外，在 6、7 年前的代码库上，就已经存在这段代码了。服务器本地也不存在 brmidyrvj.php 文件，感觉注入这个代码没有任何的价值。

**Comment by Bay0net** [comment]
好的，十分感谢，祝生活愉快~

**Comment by Bay0net** [comment]
问题已解决，不是被攻击者插入了恶意代码，是其他原因造成的，无危害。

BTW，感谢博主的回复。
